--Created BANK Table using CREATE Command 
CREATE TABLE BANK(
    ACCOUNT_ID INT UNSIGNED PRIMARY KEY,
    ACCOUNT_HOLDER_NAME VARCHAR(20) NOT NULL ,
    ADDRESS MEDIUMTEXT NULL,
    IFSC_CODE VARCHAR(30) UNIQUE, CHECK(LENGTH(IFSC_CODE)=11),
    BID INT NOT UNSIGNED NULL ,
    CONSTRAINT FOREIGN KEY(BID) BRANCH(BID)
);

--Altered BANK TABLE 

ALTER TABLE BANK --Renamed the BANK Table into BANK_DETAILS Table
RENAME BANK_DETAILS;

ALTER TABLE BANK_DETAILS 
MODIFY IFSC_CODE CHAR(30) NOT NULL;
 
ALTER TABLE BANK_DETAILS
ADD ID INT NOT NULL  ;

ALTER TABLE BANK_DETAILS
ADD  FOREIGN KEY(ID) REFERENCES STUDENT(ID);
