--Created BRANCH Table using CREATE Command 
CREATE TABLE BRANCH (
    BID INT UNSIGNED PRIMARY KEY ,
    BNAME VARCHAR(20) NOT NULL ,
    LOC VARCHAR(20) NOT NULL , 
    PINCODE INT UNSIGNED NOT NULL UNIQUE,CHECK(LENGTH(PINCODE)=6)
);
