--Created CUSTOMER Table using CREATE Command 
CREATE TABLE CUSTOMER(
    CID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    CNAME VARCHAR(20) NOT NULL ,
    PHONE BIGINT UNSIGNED NOT NULL UNIQUE ,
    ADDRESS MEDIUMTEXT NOT NULL ,
    EMAIL VARCHAR(30) NULL,
    BALANCE DECIMAL(6,2) NOT NULL,
    GENDER ENUM("MALE","FEMALE") NOT NULL ,
    FID INT UNSIGNED NOT NULL ,
    CONSTRAINT FOREIGN KEY(FID) REFERENCES FACULTY(FID)
);
