--Created FACULTY Table using CREATE Command

CREATE TABLE FACULTY(
    FID INT UNSIGNED PRIMARY KEY,
    FNAME VARCHAR(20) NOT NULL ,
    DNAME VARCHAR(20) NOT NULL ,
    PHONE BIGINT  UNSIGNED NOT NULL UNIQUE , CHECK(LENGTH(PHONE)=10)
);