--Created ORDERS Table using CREATE Command

CREATE TABLE ORDERS(
    ORDER_ID INT UNSIGNED PRIMARY KEY,
    ORDER_DATE DATE NOT NULL ,
    DELIVERY_DATE DATE NOT NULL,
    ADDRESS MEDIUMTEXT NOT NULL ,
    ID INT UNSIGNED NOT NULL ,
    CONSTRAINT FOREIGN KEY(ID) REFERENCES STUDENT(ID)
);

