--Created PRODUCT TABLE using CREATE Command 
CREATE TABLE PRODUCT (
    PID INT UNSIGNED PRIMARY KEY,
    PNAME VARCHAR(20) NOT NULL ,
    PRICE DECIMAL(5,2) NOT NULL CHECK(PRICE>0),
    MFD_DATE DATE NOT NULL ,
    QUANTITY INT UNSIGNED NOT NULL CHECK(QUANTITY>0)
) ;

--Altered PRODUCT Table 
ALTER TABLE PRODUCT
DROP MFD_DATE;