--Created STUDENT Table using CREATE command

CREATE TABLE STUDENT(
    ID INT UNSIGNED PRIMARY KEY ,
    NAME VARCHAR(10) NOT NULL,
    PHONE BIGINT UNSIGNED UNIQUE , CHECK(LENGTH(PHONE)=10)
);

--Altered(Modifying) the STUDENT Table using ALTER 

ALTER TABLE STUDENT --Added new EMAIL column in STUDENT Table
ADD EMAIL VARCHAR(20) NULL ;

ALTER TABLE STUDENT --Added new BALANCE column After NAME Column in STUDENT Table
ADD BALANCE DECIMAL(6,3) NOT NULL AFTER NAME;

ALTER TABLE STUDENT --Changed NAME Column into SNAME 
CHANGE NAME SNAME VARCHAR(10) NOT NULL;